units:
  cx: 18  # Kailh Choc keycap width (17.5mm) + 0.5mm
  cy: 17  # Kailh Choc keycap height (16.5mm) + 0.5mm
points:
  key:
    # Vertical spacing between keys in a column.
    padding: cy  # Choc keycap size plus 0.5mm.
  zones:
    four_fingers:
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
        ring:
          spread: cx
          stagger: 16
        middle:
          spread: cx
          stagger: 10
        index:
          spread: cx
          stagger: -8
        inner:
          spread: cx
          stagger: -2
    thumb:
      anchor:
        ref: four_fingers_inner_bottom
        shift: [-0.5 * cx, -cy - 2]
      rows:
        thumb:
      columns:
        left:
          stagger: 0
          rotate: 5
        home:
          spread: cx + 2.2
          stagger: -5
          rotate: -20
        right:
          spread: cx + 2.5
          stagger: -6
          rotate: -25
